### PR TITLE
VHPI support for reals

### PR DESCRIPTION
**Pull request by chiggs**
Note that VHPI seems to be broken on Aldec, I assume because the `dut` handle we get back is one level above the real toplevel?

### CODE REVIEW

**Comment by stuarthodgson** [comment]
@chiggs Both the mixed_language and test_iteration work fine on Aldec.

Problem is in part of the discovery.

```
# COUT:      0.00ns DEBUG    ..tine.assign_double.0x2af033022310       decorators.py:193  in send                            Sending trigger None
# COUT:      0.00ns DEBUG    cocotb.gpi                                  gpi_embed.c:277  in embed_sim_init                  _initialise_testbench successful
# COUT:      0.00ns DEBUG    cocotb.gpi                                 GpiCbHdl.cpp:124  in run_callback                    Generic run_callback
# COUT:      0.00ns DEBUG    ..tine.assign_double.0x2af033022310       decorators.py:193  in send                            Sending trigger Timer(1ps)
# COUT:      0.00ns INFO     cocotb.test                               test_reals.py:21   in assign_double                   Setting the value 7.0744e+307
# COUT:      0.00ns DEBUG    cocotb.gpi                                GpiCommon.cpp:192  in gpi_get_handle_by_name          Searching for stream_in_real
# COUT:      0.00ns DEBUG    cocotb.gpi                                GpiCommon.cpp:197  in gpi_get_handle_by_name          Checking if stream_in_real native though impl VHPI 
# COUT:      0.00ns CRITICAL cocotb.gpi                                VhpiCbHdl.cpp:92   in initialise                      Failed to determine size of signal object sample_module.stream_in_real
# COUT:      0.00ns DEBUG    cocotb.gpi                                GpiCommon.cpp:207  in gpi_get_handle_by_name          Found stream_in_real via VHPI
# COUT:      0.00ns DEBUG    cocotb.sample_module.stream_in_real           handle.py:87   in __init__                        Created
# COUT:      0.00ns DEBUG    cocotb.gpi                                 GpiCbHdl.cpp:126  in run_callback                    Generic run_callback done
# COUT:      0.00ns DEBUG    cocotb.gpi                                 GpiCbHdl.cpp:124  in run_callback                    Generic run_callback
# COUT:      0.00ns DEBUG    ..tine.assign_double.0x2af033022310       decorators.py:193  in send                            Sending trigger Timer(1ps)
# COUT:      0.00ns DEBUG    cocotb.gpi                                GpiCommon.cpp:192  in gpi_get_handle_by_name          Searching for stream_out_real
# COUT:      0.00ns DEBUG    cocotb.gpi                                GpiCommon.cpp:197  in gpi_get_handle_by_name          Checking if stream_out_real native though impl VHPI 
# COUT:      0.00ns CRITICAL cocotb.gpi                                VhpiCbHdl.cpp:92   in initialise                      Failed to determine size of signal object sample_module.stream_out_real
# COUT:      0.00ns DEBUG    cocotb.gpi                                GpiCommon.cpp:207  in gpi_get_handle_by_name          Found stream_out_real via VHPI
# COUT:      0.00ns DEBUG    ..otb.sample_module.stream_out_real           handle.py:87   in __init__                        Created
# COUT:      0.00ns ERROR    ..tine.assign_double.0x2af033022310           result.py:51   in raise_error                     Send raised exception: float() argument must be a string or a number
# COUT:                                                                                                                        File "/home/stuart/git/pv/cocotb_stu/cocotb/decorators.py", line 194, in send
# COUT:                                                                                                                          return self._coro.send(value)
# COUT:                                                                                                                        File "/home/stuart/git/pv/cocotb_stu/tests/test_cases/issue_134/test_reals.py", line 24, in assign_double
# COUT:                                                                                                                          got = float(dut.stream_out_real)
# COUT:                                                                                                                      
# COUT:      0.00ns DEBUG    cocotb.scheduler                           scheduler.py:523  in finish_test                     finish_test called with TestError('Send raised exception: float() argument must be a string or a number',)
# COUT:      0.00ns DEBUG    cocotb.gpi                                 GpiCbHdl.cpp:126  in run_callback                    Generic run_callback done
# COUT:      0.00ns DEBUG    cocotb.gpi                                 GpiCbHdl.cpp:124  in run_callback                    Generic run_callback
# COUT:      0.00ns ERROR    cocotb.regression                         regression.py:238  in handle_result                   Test Failed: assign_double (result was TestError)
# COUT:      0.00ns ERROR    cocotb.regression                         regression.py:159  in tear_down                       Failed 1 out of 1 tests (0 skipped)
# COUT:      0.00ns INFO     cocotb.regression                         regression.py:168  in tear_down                       Shutting down...
# COUT:      0.00ns DEBUG    cocotb.gpi                                 GpiCbHdl.cpp:126  in run_callback                    Generic run_callback done
```

We find the object fine but then can not get the size of the object to set up storage to be used later for fetching as binary. Thats easy as just call initialise(). 

Next problem is that we do not indicate to python that the signal is of type simulator.REAL and so try and assign/query using the binary method. This is because the signal shows up as a vhpiPortDeclK so we indicate it as a GPI_REGISTER.

**Comment by chiggs** [comment]
@stuarthodgson sorry being a tard - I guess that's what you get for trying to code before breakfast!

**Comment by stuarthodgson** [comment]
I'm not sure what the fix is though. Override the type passed into VpiSignalObjHdl with GPI_REAL if we detect it is a real?

**Comment by chiggs** [comment]
With 7853875 this works on Aldec

**Pull request merged**
